### ISSUE TITLE
Documentation: how to access messages

### ISSUE THREAD

**Issue by qirtaiba** [Conver/class.bitmessage.php#5]
How do you use the class to access messages in the inbox? Do you have a simple code example for this?

Thanks.

**Comment by Conver** [comment]
https://github.com/Conver/class.bitmessage.php/blob/master/class.bitmessage.php#L187-L203


`$inbox = $bitmessageObj->getAllInbox();`

**Comment by qirtaiba** [comment]
Thanks.
